### ISSUE TITLE
Does critical error need to report UEC to RAS?

### ISSUE THREAD

**Issue by WuLing-Yang** [riscv/riscv-double-trap#40]
If a critical error occurs, should the core stall the pipeline and report the Uncorrected Error Critical (UEC) to the RAS unit?

**Comment by ved-rivos** [comment]
The critical error state entered as a result of an unexpected trap. The unexpected trap may be due to a hardware error exception which is an exception that occurs when corrupted or uncorrectabe data is accessed by  an instruction. Such hardware errors that  raised the hardware error exception may report an RAS error. However entering  critical error state by itsef is not considered a hardware error and as such not reported as a RAS error.

**Comment by ved-rivos** [comment]
Hope that helped.
